### ISSUE TITLE
Feature request: Abbreviated mnemonic

### ISSUE THREAD

**Issue by IcePee** [simplycash/simplycashwallet#4]
Hello,
I love your app. The only thing is when restoring the seed I would like to be able to do this with an abbreviated 4-letter BIP39. Please see: #https://github.com/ElementsProject/libwally-core/issues/89#issue-413591462.

**Comment by simplycash** [comment]
Thanks for your feedback. Will do, together with the next major update, which will take quite a while.

**Comment by simplycash** [comment]
Implemented in v0.0.97
